---
Exception (message='test_exception'):
  Exception#message: Boo!
  Exception#cause: 
